# Use the syntax indicated in the following example
#/ example$/d
/ be$/d
/ co$/d
/ com$/d
/ do$/d
/ gov$/d
/ have$/d
/ html$/d
/ https$/d
/ ll$/d
/ ly$/d
/ org$/d
/ re$/d
/ twitterhandle$/d
/ utm_campaign=64483$/d
/ utm_medium=social&utm_source=truthsocial$/d
/ utm_source=89384$/d
/ utm_source=bg1$/d
/ utm_source=cb&utm_medium=djd$/d
/ utm_source=ddg1$/d
/ utm_source=ds21$/d
/ utm_source=je99&utm_medium=twitter$/d
/ utm_source=truthsocial$/d
/ ve$/d
/ www$/d
