#!/bin/bash

truthbrush statuses RepMattGaetz > RepMattGaetz.json
truthbrush statuses infowars > infowars.json
truthbrush statuses allidoisowen > allidoisowen.json
truthbrush statuses RobbyStarbuck > RobbyStarbuck.json
truthbrush statuses surgrn62 > surgrn62.json
truthbrush statuses LandonStarbuck > LandonStarbuck.json
truthbrush statuses RepMTG > RepMTG.json
truthbrush statuses OAN > OAN.json
truthbrush statuses repgregsteube > repgregsteube.json
truthbrush statuses RepTiffany > RepTiffany.json
truthbrush statuses NewsMax > NewsMax.json
truthbrush statuses RepBrianBabin > RepBrianBabin.json
truthbrush statuses TroyJackson > TroyJackson.json
truthbrush statuses Jim13AZ > Jim13AZ.json
truthbrush statuses JackPosobiec > JackPosobiec.json
truthbrush statuses gatewaypundit > gatewaypundit.json
truthbrush statuses realamericasvoice > realamericasvoice.json
truthbrush statuses epochtimes > epochtimes.json
truthbrush statuses RepClyde > RepClyde.json
truthbrush statuses conceptualjames > conceptualjames.json
truthbrush statuses RepEliCrane > RepEliCrane.json
truthbrush statuses warrendavidson > warrendavidson.json
truthbrush statuses marklevinshow > marklevinshow.json
truthbrush statuses ScottPresler > ScottPresler.json
truthbrush statuses TheDonaldTrump > TheDonaldTrump.json
truthbrush statuses CitizenFreePress > CitizenFreePress.json
truthbrush statuses FoxNews > FoxNews.json
truthbrush statuses maxjett12 > maxjett12.json
truthbrush statuses repandybiggsaz > repandybiggsaz.json
truthbrush statuses RepClayHiggins > RepClayHiggins.json
truthbrush statuses realDonaldTrump > realDonaldTrump.json
truthbrush statuses SteveBannonsWarRoom > SteveBannonsWarRoom.json
truthbrush statuses TheWashingtonPundit > TheWashingtonPundit.json
truthbrush statuses lancewallnau > lancewallnau.json
truthbrush statuses BuckSexton > BuckSexton.json
truthbrush statuses ClayAndBuck > ClayAndBuck.json
truthbrush statuses Jamie_Comer > Jamie_Comer.json
truthbrush statuses newdiscourses > newdiscourses.json
truthbrush statuses Qanon76 > Qanon76.json
truthbrush statuses QAnnon > QAnnon.json
truthbrush statuses proudboysNJ > proudboysNJ.json
truthbrush statuses UpstateVoice > UpstateVoice.json
truthbrush statuses republicanstrumpfans > republicanstrumpfans.json
truthbrush statuses TonyGrimmsTales > TonyGrimmsTales.json
truthbrush statuses brandongill > brandongill.json
truthbrush statuses danielledsouzagill > danielledsouzagill.json
truthbrush statuses EricTrump > EricTrump.json
truthbrush statuses DonaldJTrumpJr > DonaldJTrumpJr.json
truthbrush statuses glennbeck > glennbeck.json
truthbrush statuses AlexJones > AlexJones.json
truthbrush statuses GOPMajorityWhip > GOPMajorityWhip.json
truthbrush statuses MIGOP > MIGOP.json
truthbrush statuses vivekgramaswamy > vivekgramaswamy.json
truthbrush statuses DC_Draino > DC_Draino.json
truthbrush statuses JohnRich > JohnRich.json
truthbrush statuses seanhannity > seanhannity.json
truthbrush statuses shaneyyricch > shaneyyricch.json
truthbrush statuses repmeuser > repmeuser.json
truthbrush statuses CongressmanLaMalfa > CongressmanLaMalfa.json
truthbrush statuses RepRosendale > RepRosendale.json
truthbrush statuses republicanparty > republicanparty.json
truthbrush statuses JennaEllisEsq > JennaEllisEsq.json
truthbrush statuses AmericanAF > AmericanAF.json
truthbrush statuses HouseGOP > HouseGOP.json
truthbrush statuses breitbartnews > breitbartnews.json
truthbrush statuses Kash > Kash.json
truthbrush statuses AmericaFirstLegal > AmericaFirstLegal.json
truthbrush statuses DineshDSouza > DineshDSouza.json
truthbrush statuses BrandonStraka > BrandonStraka.json
truthbrush statuses tednugent > tednugent.json
truthbrush statuses marklevinshow > marklevinshow.json
truthbrush statuses RSBN > RSBN.json
truthbrush statuses MelaniaTrump > MelaniaTrump.json
truthbrush statuses TomFitton > TomFitton.json
truthbrush statuses Bob_Eckert > Bob_Eckert.json
truthbrush statuses Charliekirk > Charliekirk.json
truthbrush statuses northwall > northwall.json
truthbrush statuses truthsocial > truthsocial.json
truthbrush statuses jncojok > jncojok.json
truthbrush statuses catturd2 > catturd2.json
truthbrush statuses JewelsJones > JewelsJones.json
truthbrush statuses rabcl12 > rabcl12.json
truthbrush statuses therealkidrock > therealkidrock.json
truthbrush statuses LaraTrump > LaraTrump.json
truthbrush statuses TeamTrump > TeamTrump.json
truthbrush statuses gopjosh > gopjosh.json
truthbrush statuses laralogan > laralogan.json
truthbrush statuses loudobbs > loudobbs.json
truthbrush statuses DiamondandSilk > DiamondandSilk.json
truthbrush statuses DavesGreatJourney > DavesGreatJourney.json
truthbrush statuses Republican_Fighter > Republican_Fighter.json
truthbrush statuses conservativebarbie > conservativebarbie.json
truthbrush statuses ConservativeBrief > ConservativeBrief.json
truthbrush statuses ROHLL5 > ROHLL5.json
truthbrush statuses FDRLST > FDRLST.json
truthbrush statuses ResisttheMainstream > ResisttheMainstream.json
truthbrush statuses ThePatriotVoice > ThePatriotVoice.json
truthbrush statuses DCTheMan > DCTheMan.json
truthbrush statuses gracechong > gracechong.json
truthbrush statuses JudicialWatch > JudicialWatch.json
